#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
# Story Type

while IFS=: read -r username password userid groupid info homedir commandshell
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $commandshell. $userid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
